version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=a-string-secret-at-least-256-bits-long
      - PORT=3000
    volumes:
      - ./db:/usr/src/app/db
